kubernetes:
  enabled: true
  accounts:
    - name: kubernetes
      providerVersion: v2
      serviceAccount: true
      namespaces:
        - ${NAMESPACE}

artifacts:
  s3:
    enabled: ${S3_ENABLED}
    accounts:
    - name: armory-config-s3-account
  gcs:
    enabled: ${GCS_ENABLED}
    accounts:
    - name: armory-config-gcs-account
