kubernetes:
  enabled: true
  accounts:
    - name: kubernetes
      providerVersion: v2
      kubeconfigFile: /opt/spinnaker/credentials/default/kubeconfig
      namespaces:
        - ${NAMESPACE}

artifacts:
  s3:
    enabled: true
    accounts:
    - name: armory-config-s3-account
