kubernetes:
  enabled: true
  accounts:
    - name: kubernetes
      providerVersion: v2
      serviceAccount: ${USE_SERVICE_ACCOUNT}
      namespaces:
        - ${NAMESPACE}
      ${KUBECONFIG_CONFIG_ENTRY}

artifacts:
  s3:
    enabled: ${S3_ENABLED}
    accounts:
    - name: armory-config-s3-account
      apiEndpoint: ${MINIO_ENDPOINT}
      apiRegion: us-east-1
  gcs:
    enabled: ${GCS_ENABLED}
    accounts:
    - name: armory-config-gcs-account

services:
  deck:
    gateUrl: ${services.deck.protocol}://${services.deck.hostname}/api
    deckUrl: ${services.deck.protocol}://${services.deck.hostname}

