kubernetes:
  enabled: true
  accounts:
    - name: kubernetes
      providerVersion: v2
      kubeconfigFile: /opt/spinnaker/credentials/default/kubeconfig
      namespaces:
        - ${NAMESPACE}

artifacts:
  s3:
    enabled: ${S3_ENABLED}
    accounts:
    - name: armory-config-s3-account
  gcs:
    enabled: ${GCS_ENABLED}
    accounts:
    - name: armory-config-gcs-account
